### ISSUE TITLE
Confirm BSD usage

### ISSUE THREAD

**Issue by andig** [basvdlei/gotsmart#6]
Hello @basvdlei I'd like to use your DSMR parser implementation as part of https://github.com/evcc-io/evcc/pull/3284. According to the BSD license it seems as if this would require your approval. I'd appreciate if it could be given?

One small suggestion to simplify the usage of the code as library would be to provide a 

    DataObject.FloatValue() (float64, error)

method that should parse the value string and handle units to return derived base unit (i.e. multiply/divide by 1e3).

**Comment by andig** [comment]
Solved by https://github.com/evcc-io/evcc/pull/3284/commits/46962542e29b48260dda0a64c0b4c1ef4dbd5300

**Comment by basvdlei** [comment]
@andig looks like an interesting project, hope it works out for you.

Note, I'm not a lawyer. I use BSD-3 because it's the same license as Go (and the standard library). You don't need explicit approval to use BSD-3 licensed code. You just have to provide credit and the original copyright notice. Eg. by providing the sources or an "open source licences" page/command if you just ship a binary (eg like chrome does with chrome://credits). The only thing that is explicitly now allowed is the usage of my name to promote your software.

Thanks for the suggestion. The package structure was not really setup to be used as a library. I might refactor it.

**Comment by andig** [comment]
> I use BSD-3 because it's the same license as Go (and the standard library). You don't need explicit approval to use BSD-3 licensed code. You just have to provide credit and the original copyright notice.

Thank you, figured that out eventually... I'll see that we improve further and also add a credits page. Much appreciated!
